language: node_js
node_js:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - 5.1
  - 5.0
  - 4.9
  - 4.8
  - 4.7
  - 4.6
  - 4.5
  - 4.4
  - 4.3
  - 4.2
  - 4.1
  - 4.0
  - 0.12
  - 0.11
  - 0.10
  - 0.8
  - 0.6
  - iojs
before_script: npm install
script: npm test
